[package]
name = "rust-api-validation-playground"
version = "0.1.0"
authors = ["Dmytrii Nagirniak <dnagir@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "*"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
validator = "*"
validator_derive = "*"
